### ISSUE TITLE
force list entries to be unique in descriptor

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#574] opened 2020-01-15 19:45 UTC
## Purpose

adding `"unique-items": true|false` to the schema for items with `"list": true` would allow us to specify that there must not be \*plicates in the generated/provided list.

## Context

This is especially valuable when simulating a command-line or generating random values for a given set of parameters where it may not make sense to specify the same value multiple times

## Possible Implementation

As above, but importantly this also needs to be accounted for in the validator and simulator

**Comment by glatard** [comment] 2020-01-16 17:43
This should also be added to the validator and schema (not only to the simulation).

**Comment by glatard** [comment] 2020-01-29 17:23
Duplicate of #337

**Closed by glatard** 2020-01-29 17:23 UTC
Labels: duplicate, enhancement
