### ISSUE TITLE
descriptor2func can't handle duplicate command-line flags

### ISSUE THREAD

**Issue by EdThe** [boutiques/boutiques#548] opened 2019-10-15 20:46 UTC
When a descriptor has 2 inputs with the same command-line flag, it is able to run correctly using the command line 'bosh', but when 'descriptor2func''s 'function()' is called, it causes an error.

## Current Behavior
This happens with any 2 inputs with similar command-line flags.
```

        {
            "command-line-flag": "-step",
            "description": "Set the step size of the algorithm in mm (default is 0.1 x voxelsize).",
            "id": "step_default",
            "name": "Default step",
            "optional": true,
            "type": "Number",
            "disables-inputs": ["step_iFOD2"],
            "value-key": "[STEP_DEFAULT]"
        },
        {
            "command-line-flag": "-step",
            "description": "Set the step size of the algorithm in mm (default for iFOD2: 0.5 x voxelsize).",
            "id": "step_iFOD2",
            "name": "iFOD2 step",
            "optional": true,
            "type": "Number",
            "disables-inputs": ["step_default"],
            "value-key": "[STEP_IFOD2]"
        },
```
Even though the inputs are both optional and without any default values, when 'function()' is called with a descriptor that has 2 similar inputs like these, we get the error:
```Traceback (most recent call last):
  File "mrtrixPpline.py", line 78, in <module>
    main()
  File "mrtrixPpline.py", line 26, in main
    tckgen = function("tckgen_desc.json")
  File "/home/ed/.local/lib/python3.6/site-packages/boutiques/descriptor2func.py", line 55, in function
    doc.append(prettyprint(descriptor))
  File "/home/ed/.local/lib/python3.6/site-packages/boutiques/bosh.py", line 34, in prettyprint
    prettyclass = PrettyPrinter(desc)
  File "/home/ed/.local/lib/python3.6/site-packages/boutiques/prettyprint.py", line 15, in __init__
    self.createHelpText()
  File "/home/ed/.local/lib/python3.6/site-packages/boutiques/prettyprint.py", line 41, in createHelpText
    self.descInputs()
  File "/home/ed/.local/lib/python3.6/site-packages/boutiques/prettyprint.py", line 324, in descInputs
    self.parser.add_argument(*inp_args, **inp_kwargs)
  File "/usr/lib/python3.6/argparse.py", line 1361, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1724, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1565, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1375, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.6/argparse.py", line 1514, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.6/argparse.py", line 1523, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -step: conflicting option string: -step
```

## Location of the bug
This seems to be caused by the documentation part of the method 'function' (when it uses prettyprint). If documentation requires all possible inputs to be shown, then it would not be possible to simply check and ensure no repetition.

**Comment by glatard** [comment] 2019-10-16 14:08
@DarrinFong, would you be able to look at this once you're done with your current task?

**Comment by glatard** [comment] 2019-10-16 14:15
This is also a duplicate of #516 (thanks for pointing this out @ValHayot!)

**Comment by DarrinFong** [comment] 2019-10-22 18:56
Hi, I'm looking at this and am not sure what should be the fix. 
The obvious and easy fix is to change the name of all subsequent duplicate flags, but it should be clear the subsequent duplicates have to be identical to the first in CLI. Are there any better alternatives?

**Closed** 2019-11-05 17:27 UTC
Labels: bug
