### ISSUE TITLE
Add required-by property on output-files

### ISSUE THREAD

**Issue by ramou** [boutiques/boutiques#512] opened 2019-06-10 20:22 UTC
## Purpose
Currently there is no way to specify that output files are only required if certain inputs are used, but this is a common practice. [makeblastdb](https://github.com/bioinformatics-group/BoutiquesDescriptors/blob/master/ncbi-blast/2.7.1/makeblastdb.json) uses `-parse_seqids` to indicate that when generating database files, a `.psi` if the `-dbtype=prot`.

## Context
Currently I must specify output files so generically that the validation is not very helpful.

## Preferred solution (optional)
At a minimum, I would like a `required-by` to indicate when a single input creates the need for an output file. 

## Alternatives solutions (optional)
It would also be nice to support required-by for multiple inputs, but a distinction would need to be made as to whether any or all inputs were needed to require the given output.

## Possible Implementation (optional)
The existing group rules might be relevant here. If we could have groups of outputs, then the rules could apply to the group, such that an output file is required if one-of a set of inputs were used. If this could be aggregate and/or complex, then even better, but I'm not sure if its been settled how to do that with inputs, or if we have a good means to validate automatically (or if we'd have to write custom validation). I haven't got further than this on technical implementation details.

**Comment by glatard** [comment] 2019-06-12 21:01
This is very much linked to #503. Let's discuss it, perhaps at the next meeting, propose something, run it by @satra and @leej3, and do it!

**Comment by glatard** [comment] 2019-07-22 14:23
This is now a duplicate of #303.

**Closed by glatard** 2019-07-22 14:23 UTC
Labels: enhancement
