### ISSUE TITLE
API should support passing descriptors and invocations as JSON objects instead of files

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#213] opened 2018-02-06 21:40 UTC
It feels like `bosh` should accept JSON objects read from the main method.

**Comment by gkiar** [comment] 2018-02-07 04:23
Agreed!

**Comment by erinb90** [comment] 2018-09-25 20:13
Is this a duplicate of #277?

**Comment by glatard** [comment] 2018-09-26 14:14
Related but not duplication: #277 is about the CLI, this is for the API. Does your PR address both?

**Comment by erinb90** [comment] 2018-09-27 15:45
@glatard Yes, with my changes we are able to pass JSON objects either by the CLI or using the API.

**Closed** 2018-12-07 01:20 UTC
Labels: enhancement, good first issue
